apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-js
  template:
    metadata:
      labels:
        app: react-js
    spec:
      containers:
      - name: react-js
        image: eovnstd/ipl_client
        ports:
        - containerPort: 3000
        # env:
        # - name: REACT_APP_BASE_URL
        #   value: ""
        # - name: BACKEND_URL
        #   value: "http://server-deployment:5000"
        # command: ["sh", "-c", "echo REACT_APP_BASE_URL=http://$(kubectl get service node-js-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):5000 > .env && npm start"]
---
apiVersion: v1
kind: Service
metadata:
  name: react-js-service
spec:
  type: LoadBalancer
  selector:
    app: react-js
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
