- name: Pull docker image ipl
  hosts: all
  tasks:
  
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: copy server deployment file from folder to remote host
      copy:
        src: ./server-deployment.yaml
        dest: ./

    - name: copy backend service file from folder to remote host
      copy:
        src: ./backend-service.yaml
        dest: ./

    - name: copy client deployment file from folder to remote host
      copy:
        src: ./client-deployment.yaml
        dest: ./
        
    - name: pull docker server image
      shell: docker pull eovnstd/ipl_server

    - name: pull docker client image
      shell: docker pull eovnstd/ipl_client

    - name: run the server menifest file
      shell: kubectl apply -f server-deployment.yaml

    - name: run the backend-service menifest file
      shell: kubectl apply -f backend-service.yaml
    
    - name: get Node.js service port
      shell: kubectl get service node-js-service -o jsonpath='{.spec.ports[0].nodePort}'
      register: node_js_service_port
      
    - name: Output Node.js service URL
      set_fact:
        node_js_service_url: "http://{{ ansible_host }}:{{ node_js_service_port.stdout }}"
      
    - name: run the client menifest file
      shell: kubectl apply -f client-deployment.yaml
      environment:
        REACT_APP_BASE_URL: "{{ node_js_service_url }}"
