---
- name: Pull docker image ipl
  hosts: all
  tasks:
  
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: copy server deployment file from folder to remote host
      copy:
        src: ./server-deployment.yml
        dest: ./

    - name: copy backend service file from folder to remote host
      copy:
        src: ./backend-service.yaml
        dest: ./

    - name: copy client deployment file from folder to remote host
      copy:
        src: ./client-deployment.yml
        dest: ./
        
    - name: pull docker server image
      shell: docker pull eovnstd/ipl_server

    - name: pull docker client image
      shell: docker pull eovnstd/ipl_client

    - name: run the server menifest file
      shell: kubectl apply -f server-deployment.yml

    - name: run the backend-service menifest file
      shell: kubectl apply -f backend-service.yaml
    
    - name: get URL of Node.js service
      shell: minikube service node-js-service --url
      register: node_js_service_url
    
    - name: run the client menifest file
      shell: kubectl apply -f client-deployment.yml
      environment:
        REACT_APP_BASE_URL: "{{ node_js_service_url.stdout }}"
      
    
