- name: Pull docker image ipl
  hosts: all
  tasks:
  
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: copy server deployment file from folder to remote host
      copy:
        src: ./server-deployment.yaml
        dest: ./

    - name: copy backend service file from folder to remote host
      copy:
        src: ./backend-service.yaml
        dest: ./

    - name: copy client deployment file from folder to remote host
      copy:
        src: ./client-deployment.yaml
        dest: ./
        
    - name: pull docker server image
      shell: docker pull eovnstd/ipl_server

    - name: pull docker client image
      shell: docker pull eovnstd/ipl_client

    - name: run the server manifest file
      shell: kubectl apply -f server-deployment.yaml

    - name: run the backend service manifest file
      shell: kubectl apply -f backend-service.yaml
    
    - name: get URL of backend service
      shell: minikube service backend-service --url
      register: backend_service_url
      
    - name: Output backend service URL
      shell: echo "{{ backend_service_url.stdout }}"

    - name: run the client manifest file
      shell: kubectl apply -f client-deployment.yaml
      environment:
        REACT_APP_BASE_URL: "{{ backend_service_url.stdout }}"
