- name: Pull docker image ipl
  hosts: all
  tasks:

    - name: delete existing pods
      shell: kubectl delete all --all

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker server image
      shell: docker pull eovnstd/ipl_server

    - name: pull docker client image
      shell: docker pull eovnstd/ipl_client

    - name: copy yaml files for kubectl
      copy: 
        src: ./elk/
        dest: ./
    
    - name: elevate permissions for kube.sh
      shell: chmod 766 kube.sh
    - name: run kube.sh
      shell: ./kube.sh

