- name: Pull docker image ipl
  hosts: all
  tasks:

    - name: delete existing pods
      shell: kubectl delete po --all

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: copy docker compose file
      copy: 
        src: ./docker-compose.yml
        dest: ./

    - name: copy server-client deployment file from folder to remote host
      copy:
        src: ./server-client-deployment.yaml
        dest: ./
    
    
    - name: run Docker Compose file
      docker_compose:
        project_src: ./docker-compose.yml

    - name: pull docker server image
      shell: docker pull eovnstd/ipl_server

    - name: pull docker client image
      shell: docker pull eovnstd/ipl_client

    - name: run the server manifest file
      shell: kubectl apply -f server-client-deployment.yaml
    
    - name: copy port forward file
      copy:
        src: ./pf.sh
        dest: ./
    - name: port forward server, client
      shell: sh pf.sh -d

