- name: Pull docker image ipl
  hosts: all
  tasks:

    - name: delete existing pods
      shell: kubectl delete all --all

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: copy server-client deployment file from folder to remote host
      copy:
        src: ./server-client-deployment.yaml
        dest: ./
    - name: copy elk folder to run elk
      copy:
        src: ./elk/
        dest: ./

    - name: pull docker server image
      shell: docker pull eovnstd/ipl_server

    - name: pull docker client image
      shell: docker pull eovnstd/ipl_client

    - name: run the server manifest file
      shell: kubectl apply -f ./
    

