apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
      - name: node-js
        image: ipl_server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: node-js-service
  labels:
    app: node-js
spec:
  type: LoadBalancer
  selector:
    app: node-js
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
