apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: node-js
    image: eovnstd/ipl_server
    ports:
      - containerPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
spec:
  containers:
  - name: react-js
    image: eovnstd/ipl_client
    ports:
      - containerPort: 3000


