apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-volume
  labels:
    io.kompose.service: elasticsearch-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
